### ISSUE TITLE
Save and cancel buttons do not work when editing an article from the front end

### ISSUE THREAD

**Issue by nzealand** [nternetinspired/OneWeb#5]
Navigate to http://joomla.website.com/index.php/component/users/?view=login

Login to website.

The end user website is now enabled with a pencil icon to allow the editing of articles.

Clicking the edit icon results in a text editor appearing, but the Save & Cancel buttons do not work.

Switching to another template resolves the issue.

This issue was also noted here: http://forum.joomla.org/viewtopic.php?f=615&t=722240

**Comment by nternetinspired** [comment]
This is almost certainly because you have mootools loading disabled in the template settings. Mootools is still required for front-end editing unfortunately.

My advice, don't edit from the front-end and save 100's of Kb on page load ;) If you need front-end editing you will need to re-enable mootools.

**Comment by nzealand** [comment]
Adding the following to the end of helper.js resolved my issue.

if (typeof(Joomla) === 'undefined') {
    var Joomla = {};
}

Joomla.editors = {instances:{}};

Joomla.$ = function(str) {
    return document.getElementById(str) || document[str];
};

Joomla.submitbutton = function(pressbutton) {
    Joomla.submitform(pressbutton);
};

Joomla.submitform = function(task, form) {
    form = form || Joomla.$('adminForm');

```
if (typeof(task) !== 'undefined') {
    form.task.value = task;
}

// Submit the form.
if (typeof form.onsubmit == 'function') {
    form.onsubmit();
}
if (typeof form.fireEvent == 'function') {
    form.fireEvent('submit');
}
form.submit();
```

};

**Comment by nzealand** [comment]
You are correct however, I did have MooTools disabled. 

Nice work on the template btw.

**Comment by nternetinspired** [comment]
Thanks. Marking this as closed then.
